### ISSUE TITLE
API change thoughts

### ISSUE THREAD

**Issue by defunctzombie** [defunctzombie/dom-events#3]
I've been thinking about changing the api to be:

```
domev(element).on(..);
domev(element).off(..);
```

versus now

```
domev.on(elem...);
domev.off(elem...);
```

This would allow for chaining (for anyone that cares). and just seems a bit more clearer to read. Thoughts?

/cc @juliangruber @marcello3d

**Comment by juliangruber** [comment]
-1 from me, I do

``` js
var on = require('dom-events').on;
var off = require('dom-events').off;

on(el, 'event', fn);
// ...
```

**Comment by defunctzombie** [comment]
Fair enough.
